better prefix copying

diff --git a/sbox-server-no-update b/sbox-server-no-update
--- a/sbox-server-no-update
+++ b/sbox-server-no-update
@@ -1,14 +1,28 @@
 #!/bin/bash
+set -e
+
 echo Running sbox-server...
 echo Checking for a valid prefix...
-if [ -d "$HOME/.wine" ]; then
+
+export WINEPREFIX="$HOME/.wine-sbox"
+
+if [ "$EUID" -eq 0 ]; then
+    echo "Running as root - using the prefix at '/wine/prefix'"
+    export WINEPREFIX="/wine/prefix"
+fi
+
+if [ -d "$WINEPREFIX" ]; then
     echo "Found a valid prefix for this user."
 else
-    echo "Not found - initializing prefix..."
-    cp -r /wine/prefix $HOME/.wine
-    chown -R $USER: $HOME/.wine
+    if [ ! -d "/wine/prefix" ]; then
+        echo "'/wine/prefix' wasn't found!"
+        exit 1
+    fi
+
+    echo "Not found - creating a copy of '/wine/prefix'"
+    cp -r /wine/prefix "$WINEPREFIX"
+    chown -R $USER: "$WINEPREFIX"
 fi
 
 echo "Starting server..."
-export WINEPREFIX="$HOME/.wine"
 wine /wine/steamapps/sbox-server/sbox-server.exe ${SBOX_SERVER_ARGUMENTS} "$@"
